version: '3'
services:
  postgres:
    image: postgres:9.5
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TEST_SM
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/postgres/postgresql.conf:/etc/postgres/postgresql.conf
    command: -c config_file=/etc/postgres/postgresql.conf
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fabio@code137.com.br
      PGADMIN_DEFAULT_PASSWORD: 123
    restart: unless-stopped

volumes:
  postgres-data:
