language: c

script:
  - bats test
  - ./lint.sh

before_install:
  - ./prepare-travis.sh

before_script:
  - git clone https://github.com/bats-core/bats-core.git --branch v1.1.0 /tmp/bats
  - export PATH=/tmp/bats/bin:$PATH

os:
  - linux
  - osx
